<a href="https://colab.research.google.com/github/xXSyarifXx/PyTorch_Colab/blob/master/PyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
x = torch.empty(5, 3)
print(x)

tensor([[2.3417e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6550, 0.9556, 0.8975],
        [0.5455, 0.0015, 0.5763],
        [0.6177, 0.3738, 0.2562],
        [0.1139, 0.3297, 0.8724],
        [0.3821, 0.6173, 0.2069]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

y = torch.rand(5, 3)
print(x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1501,  0.9015, -0.1727],
        [-1.4885, -1.1319, -0.0052],
        [ 0.3398, -0.6187, -2.1022],
        [ 1.6529, -1.9939, -0.6089],
        [ 0.8048,  1.6454, -0.4508]])
tensor([[-0.0232,  1.5225, -0.0511],
        [-1.4071, -0.4923,  0.6240],
        [ 1.1361, -0.2586, -1.3164],
        [ 1.9386, -1.7963, -0.4170],
        [ 1.3401,  1.7281, -0.1377]])


In [0]:
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.3418e-36,  0.0000e+00,  4.4842e-44],
        [ 0.0000e+00,         nan,  6.2399e-01],
        [ 5.2941e-08,  1.7174e-07,  8.3451e-10],
        [ 5.2898e-08,  5.2897e-08,  1.3120e-08],
        [ 4.1721e-08,  2.6102e+20, -1.3769e-01]])
tensor([[-0.0232,  1.5225, -0.0511],
        [-1.4071, -0.4923,  0.6240],
        [ 1.1361, -0.2586, -1.3164],
        [ 1.9386, -1.7963, -0.4170],
        [ 1.3401,  1.7281, -0.1377]])


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))


tensor([[ 0.8499,  1.9015,  0.8273],
        [-0.4885, -0.1319,  0.9948],
        [ 1.3398,  0.3813, -1.1022],
        [ 2.6529, -0.9939,  0.3911],
        [ 1.8048,  2.6454,  0.5492]], device='cuda:0')
tensor([[ 0.8499,  1.9015,  0.8273],
        [-0.4885, -0.1319,  0.9948],
        [ 1.3398,  0.3813, -1.1022],
        [ 2.6529, -0.9939,  0.3911],
        [ 1.8048,  2.6454,  0.5492]], dtype=torch.float64)


### AUTO GRAD

In [0]:
import torch

In [0]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(dir(x))

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ilshift__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rmul__', '__rpow__', '__rshift__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__s

In [0]:
y = x + 2
print(y)
print(dir(y))

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ilshift__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rmul__', '__rpow__', '__rshift__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', 

In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()
print(z, out)


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [0]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [0]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1213.6731,  146.8996, 1560.1035], grad_fn=<MulBackward0>)
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [0]:
import torch
import numpy as np

Neural Network

In [0]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 15)
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=15, bias=True)
)


In [0]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [0]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0632,  0.0539,  0.0097, -0.1322,  0.0252,  0.0874, -0.0961, -0.0984,
          0.1133, -0.0685,  0.0048,  0.1041,  0.0728,  0.0235,  0.0948]],
       grad_fn=<AddmmBackward>)


In [0]:
net.zero_grad()
out.backward(torch.randn(1, 15))

In [0]:
output = net(input)
target = torch.randn(15) #dummy target
print(target)
target = target.view(1, -1) #making the same shape as the output
print(target)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor([ 0.8497,  0.2155,  0.7955, -0.4853,  0.0267, -0.6587,  0.6565,  2.1703,
         0.6243, -0.2382,  1.4680, -0.3782, -0.3802, -1.3496,  1.9782])
tensor([[ 0.8497,  0.2155,  0.7955, -0.4853,  0.0267, -0.6587,  0.6565,  2.1703,
          0.6243, -0.2382,  1.4680, -0.3782, -0.3802, -1.3496,  1.9782]])
tensor(1.0782, grad_fn=<MseLossBackward>)


In [0]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [0]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0019,  0.0029, -0.0023, -0.0015,  0.0007,  0.0033])
